name: "HA Download Manager"
slug: "ha_download_manager"
version: "1.0.12"
description: "Home Assistant Download Manager"

arch:
  - amd64
  - aarch64

ingress: true
ingress_port: 3000

startup: services
boot: auto

panel_icon: mdi:download
host_network: false

map:
  - media:rw

options:
  baseUrl: "https://hdrezka.me"
  download_path: /media/DOWNLOADS
  port: 3000  
  browser_pool_size: 4
  browser_nav_timeout: 60000

schema:
  baseUrl:
    - "https://hdrezka.ag"
    - "https://hdrezka.cm"
    - "https://hdrezka.me"
    - "https://hdrezka.co"
    - "https://hdrezka-home.tv"
  download_path: str
  port: port
  browser_pool_size: int
  browser_nav_timeout: int
