name: "HA Download Manager"
slug: "ha_download_manager"
version: "1.0.10"
description: "Home Assistant Download Manager"
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 3000
startup: services
boot: auto
panel_icon: mdi:download
host_network: false
map:
  - media:rw
options:
  port: 3000
  browser_pool_size: 4
  browser_nav_timeout: 60000
  download_path: /media/DOWNLOADS
schema:
  port: port
  browser_pool_size: int
  browser_nav_timeout: int
  download_path: str
